Added functionality of fetch the subscriber details
jvc931/Practice pull request #13
Opened 2017-04-26 16:51 UTC by jvc931

Added functionality of fetch the subscriber details, manage the fetch indicator and the error message dialog.

2017-04-26 17:35 UTC, daniellemariani requested changes

2017-04-26 17:35 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/presenter/SubscriberDetailsPresenter.java
> +    private String login;
What's the purpose of this attribute?

2017-04-26 17:35 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/presenter/SubscriberDetailsPresenter.java
> + * Contains the methods that the SubscriberDetailsFragment needs.
Give more context, what actions perform this class?

2017-04-26 17:35 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/presenter/SubscriberDetailsPresenter.java
> +    private Observer<Profile> getSubscriberProfile = new Observer<Profile>() {
Move attributes to the top of the class and then declare your methods

2017-04-26 17:35 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/presenter/SubscriberDetailsPresenter.java
> +            subscriberRepositoryListObservable = repositoriesInteractor.execute(login);
Extract this block to a private method: **fetchSubscriberRepositories**

2017-04-26 17:35 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/view/fragment/SubscriberDetailsFragment.java
> +        } else if (subscriberDetailsState.getProfile() != null && subscriberDetailsState.getSubscriberRepositories() != null) {
Leave a TODO comment that explains the forthcoming implementation

2017-04-26 17:35 UTC, daniellemariani commented on app/src/main/res/values-es/strings.xml
> +    <string name="subscriberlist_progress_dialog">Obteniendo detalles del suscritor, por favor espere</string>
Shouldn't it be related to Subscriber List? You're duplicating the same copy below. Also in Spanish is "suscriptor".

2017-04-26 21:31 UTC, daniellemariani requested changes

2017-04-26 21:31 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/domain/interactor/FetchSubscriberProfile.java
> +public class FetchSubscriberProfile {
Please, add Interactor suffix to this class and other interactors

2017-04-27 14:09 UTC, jvc931 commented on app/src/main/java/com/globant/practice/presentation/presenter/SubscriberDetailsPresenter.java
> + * Contains the methods that the SubscriberDetailsFragment needs.
Done.

2017-04-27 14:09 UTC, jvc931 commented on app/src/main/java/com/globant/practice/presentation/presenter/SubscriberDetailsPresenter.java
> +    private Observer<Profile> getSubscriberProfile = new Observer<Profile>() {
Done.

2017-04-27 14:10 UTC, jvc931 commented on app/src/main/java/com/globant/practice/presentation/view/fragment/SubscriberDetailsFragment.java
> +        } else if (subscriberDetailsState.getProfile() != null && subscriberDetailsState.getSubscriberRepositories() != null) {
Done.

2017-04-27 14:39 UTC, daniellemariani requested changes

2017-04-27 14:39 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/view/fragment/SubscriberDetailsFragment.java
>      private String login;
This attribute must be stored in SubscriberDetailsState

2017-04-27 14:39 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/view/fragment/SubscriberDetailsFragment.java
> +    public String getSubscriberLogin() {
This is not necessary. It may be stored inside the view state model

2017-04-27 14:39 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/view/fragment/SubscriberDetailsView.java
> +    String getSubscriberLogin();
Not necessary

2017-04-27 15:21 UTC, daniellemariani approved these changes
LG

2017-04-27 15:21 UTC, merged