Show the subscriber details on the view
jvc931/Practice pull request #14
Opened 2017-04-28 16:48 UTC by jvc931

Added the necessary views to show the subscriber details on the RecyclerView and added the adapter for this element.

2017-04-28 20:09 UTC, daniellemariani requested changes
Keep in mind that layouts consume lots of resources when the OS tries to draw them. Use them carefully.

2017-04-28 20:09 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/view/adapter/SubscriberDetailsAdapter.java
> +        return position == 0 ? 0 : 1;
Please, use constants for view types

2017-04-28 20:09 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_profile_item.xml
> +    android:layout_height="220dp"
Please, define dimensions in dimens.xml

2017-04-28 20:09 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_profile_item.xml
> +        <LinearLayout
You can remove this layout and move the properties to its child (imageview)

2017-04-28 20:09 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_profile_item.xml
> +                <LinearLayout
Same here

2017-04-28 20:09 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_profile_item.xml
> +                <LinearLayout
Same here

2017-04-28 20:09 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_profile_item.xml
> +                <LinearLayout
Same here

2017-04-28 20:09 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_profile_item.xml
> +                <LinearLayout
Same here

2017-04-28 20:09 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_profile_item.xml
> +        <LinearLayout
Please, recreate this layout to avoid the excessive number of layouts

2017-04-28 20:09 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_repositories_item.xml
> +    <LinearLayout
This linear layouts are useless. You can easily remove it and move the properties to the textviews

2017-05-02 15:44 UTC, jvc931 commented on app/src/main/res/layout/subscriber_profile_item.xml
> +        <LinearLayout
Done

2017-05-02 16:06 UTC, daniellemariani requested changes
Do not undervalue the app perfomance when creating complex ui plus adding weight attributes.

2017-05-02 16:06 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/view/adapter/SubscriberDetailsAdapter.java
> +        return position == 0 ? SUBSCRIBER_PROFILE_ITEM : SUBSCRIBER_REPOSITORY_ITEM;
Use a constant for position 0 as well. Something like **FIRST_ITEM** or **INDEX_ZERO**.

2017-05-02 16:06 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/view/adapter/SubscriberDetailsAdapter.java
> +            if (profile.getName() == null) {
Please, use TextUtils.isEmpty() to verify if a string is null or empty. The same for other cases

2017-05-02 16:06 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_repositories_item.xml
> +    android:layout_height="@dimen/subscriber_repositories_item_height"
If it is meant for a single repository item, use a singular name. E.g: _repository_
This also applies for this file name

2017-05-02 16:06 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_profile_item.xml
> +        android:layout_height="match_parent"
Height must be 0dp when working inside of a vertical linear layout

2017-05-02 16:06 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_profile_item.xml
> +            android:layout_width="match_parent"
Width must be 0dp when working inside of a horizontal linear layout

2017-05-02 16:06 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_profile_item.xml
> +    <LinearLayout
You can easily recreate this block using a relative layout with an image view and three textviews. Think in the performance when creating the UI

2017-05-02 16:06 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_repositories_item.xml
> +        android:layout_weight="0.6"
Do you really need weight?
Why don't using wrap_content for this repository "label"

2017-05-02 16:06 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_repositories_item.xml
> +        android:layout_height="match_parent"
Same here

2017-05-02 16:06 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_repositories_item.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
This could be a Relative Layout.

2017-05-02 22:17 UTC, daniellemariani requested changes
Please, provide screenshots of this screen

2017-05-02 22:17 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/view/adapter/SubscriberDetailsAdapter.java
> +                company.setText(context.getString(R.string.subscriber_details_company_txt) + " " + profile.getCompany());
You can avoid these conditionals if you use a Formatted String

2017-05-02 22:17 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/view/adapter/SubscriberDetailsAdapter.java
> +                if (onUserClickListener != null) {
Do this validation only once.

2017-05-02 22:17 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_profile_item.xml
> +        android:layout_weight="0.4"
Question. Why using a weight instead of wrap content?

2017-05-02 22:17 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_profile_item.xml
> +            android:layout_width="fill_parent"
Change this to MATCH_PARENT

2017-05-02 22:17 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_profile_item.xml
> +            android:layout_width="fill_parent"
Change this to MATCH_PARENT

2017-05-02 22:17 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_profile_item.xml
> +            android:layout_width="fill_parent"
Change this to MATCH_PARENT

2017-05-02 22:17 UTC, daniellemariani commented on app/src/main/res/values/strings.xml
> +    <string name="subscriber_details_followers">Followes:</string>
You miss the R

2017-05-02 22:17 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_profile_item.xml
> +        android:layout_weight="0.6">
Same here. Why using weight?

2017-05-02 22:17 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_profile_item.xml
> +        <TextView
Should it be below the location?

2017-05-02 22:17 UTC, daniellemariani commented on app/src/main/res/layout/subscriber_profile_item.xml
> +        <TextView
Should it be placed below the name?

2017-05-03 15:47 UTC, jvc931 commented on app/src/main/res/layout/subscriber_profile_item.xml
> +        <TextView
Done.

2017-05-03 17:01 UTC, daniellemariani requested changes

2017-05-03 17:01 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/view/adapter/SubscriberDetailsAdapter.java
> +            location.setText(String.format("%s %s", context.getString(R.string.subscriber_details_location), profile.getLocation() != null ? profile.getLocation() : ""));
Define a String resource that has this format. Example:
`<string name="test">Label: %$s<string>`

2017-05-03 17:29 UTC, daniellemariani requested changes

2017-05-03 17:29 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/view/adapter/SubscriberDetailsAdapter.java
> +            followers.setText(context.getString(R.string.subscriber_details_followers) + " " + String.valueOf(profile.getFollowers()));
Please, use a string resource format here as well, and for all similar cases

2017-05-03 18:01 UTC, daniellemariani requested changes

2017-05-03 18:01 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/view/adapter/SubscriberDetailsAdapter.java
> +        if (viewType == 0) {
Replace 0 with SUBSCRIBER_PROFILE_ITEM please

2017-05-03 18:01 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/view/adapter/SubscriberDetailsAdapter.java
> +            SubscriberDetailsViewHolder subscriberDetailsViewHolder = new SubscriberDetailsAdapter.SubscriberDetailsViewHolder(itemView);
there is no need in creating this variable

2017-05-03 18:01 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/view/adapter/SubscriberDetailsAdapter.java
> +            SubscriberDetailsViewHolder subscriberDetailsViewHolder = new SubscriberDetailsAdapter.SubscriberDetailsViewHolder(itemView);
Same here

2017-05-03 18:01 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/view/adapter/SubscriberDetailsAdapter.java
> +                if (view.getTag().equals(context.getString(R.string.subscriber_details_layout_tag))) {
Instead of using a tag, you can check the view id. Analyze it.

2017-05-03 20:47 UTC, daniellemariani requested changes

2017-05-03 20:47 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presentation/view/adapter/SubscriberDetailsAdapter.java
> +            name.setOnClickListener(this);
Set the click listener in the constructor. As you did with the repository

2017-05-03 21:30 UTC, daniellemariani approved these changes
LG

2017-05-03 21:30 UTC, merged