Unit test of SubscriberListPresenter, SubscriberDetailsPresenter, WebClientPresenter
jvc931/Practice pull request #18
Opened 2017-05-19 21:01 UTC by jvc931

Unit test of SubscriberListPresenter, SubscriberDetailsPresenter, WebClientPresenter

2017-05-19 21:59 UTC, daniellemariani requested changes

2017-05-19 21:59 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/presentation/presenter/SubscriberDetailsPresenterTest.java
> +    public void fetchSubscriberDetails_withAttachedViewAndProfileInteractorErrorResponse_ShouldShowLoadingIndicatorAndErrorMessage_ShouldNotCallRepositoriesInteractor() throws Exception {
*fetchSubscriberDetails_withViewAttachedAndProfileCallFails_ShouldRenderLoadingIndicatorAndError*

2017-05-19 21:59 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/presentation/presenter/SubscriberDetailsPresenterTest.java
> +    public void fetchSubscriberDetails_withAttachedViewAndProfileInteractorResponse_ShouldCallRepositoriesInteractor_withRepositoriesInteractorErrorResponse() throws Exception {
*fetchSubscriberDetails_withViewAttachedAndRepositoriesCallFails_ShouldRenderLoadingIndicatorAndError*

2017-05-19 21:59 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/presentation/presenter/SubscriberDetailsPresenterTest.java
> +    public void fetchSubscriberDetails_withAttachedViewAndProfileInteractorResponse_ShouldCallRepositoriesInteractor_withRepositoriesInteractorResponse() throws Exception {
fetchSubscriberDetails_withAttachedViewAndSuccessfulProfileAndRepositoryCalls_ShouldRenderProfileAndRepositories

2017-05-19 21:59 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/presentation/presenter/SubscriberDetailsPresenterTest.java
> +        verify(repositoriesInteractor, times(1)).execute(anyString());
By the default it should be 1

2017-05-19 21:59 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/presentation/presenter/SubscriberDetailsPresenterTest.java
> +        verify(repositoriesInteractor, times(1)).execute(anyString());
By default it should be 1

2017-05-19 21:59 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/presentation/presenter/SubscriberListPresenterTest.java
> +    public void fetchUsers_withViewAttachedAndWebserviceResponse_ShouldShowLoadingIndicatorAndSubscribers() throws Exception {
*fetchUsers_withViewAttachedAndSuccessfulResponse_ShouldRenderLoadingIndicatorAndSubscribers*

2017-05-19 21:59 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/presentation/presenter/SubscriberListPresenterTest.java
> +    public void fetchUsers_withViewAttachedAndWebserviceErrorResponse_ShouldShowLoadingIndicatorAndErrorMessage() throws Exception {
*fetchUsers_withViewAttachedAndResponseFails_ShouldRenderLoadingIndicatorAndError*

2017-05-19 21:59 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/presentation/presenter/WebClientPresenterTest.java
> +    public void loadWebPage_withAttachView_ShouldShowLoadingIndicatorAndLoadWebPage() throws Exception {
withViewAttached

2017-05-19 21:59 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/presentation/presenter/WebClientPresenterTest.java
> +    public void webPageLoadComplete_withAttachView_ShouldDismissLoadingIndicator() throws Exception {
withViewAttached

2017-05-19 21:59 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/presentation/presenter/WebClientPresenterTest.java
> +        verify(mockView, times(1)).render(any(WebClientState.class));
by default it should be 1

2017-05-19 21:59 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/presentation/presenter/WebClientPresenterTest.java
> +    public void webPageError_witDetachView_ShouldNotDismissLoadingIndicator() throws Exception {
You miss the **h** in with. Also, rename it to withViewDetached

2017-05-19 21:59 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/presentation/presenter/WebClientPresenterTest.java
> +    public void webPageLoadComplete_withDetachView_ShouldNotDismissLoadingIndicator() throws Exception {
withViewDetached

2017-05-19 21:59 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/presentation/presenter/WebClientPresenterTest.java
> +    public void loadWebPage_withDetachView_ShouldNotShowLoadingIndicator() throws Exception {
withViewDetached

2017-05-19 22:38 UTC, daniellemariani requested changes

2017-05-19 22:38 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/presentation/presenter/SubscriberDetailsPresenterTest.java
> +    public void fetchSubscriberDetails_withAttachedViewAndSuccessfulProfileAndRepositoryCalls_ShouldRenderProfileAndRepositories() throws Exception {
withViewAttached

2017-05-22 14:05 UTC, jvc931 commented on app/src/test/java/com/globant/practice/presentation/presenter/SubscriberDetailsPresenterTest.java
> +    public void fetchSubscriberDetails_withAttachedViewAndSuccessfulProfileAndRepositoryCalls_ShouldRenderProfileAndRepositories() throws Exception {
Done

2017-05-22 14:50 UTC, daniellemariani approved these changes
LG

2017-05-22 14:50 UTC, merged