Added SplashActivity functionality with unit test methods
jvc931/Practice pull request #3
Opened 2017-03-31 20:09 UTC by jvc931

Added SplashActivity functionality with unit test methods, initialize the HomeActivity because need to start the intent between SplashActivity and HomeActivity.

2017-03-31 20:36 UTC, daniellemariani requested changes

2017-03-31 20:36 UTC, daniellemariani commented on app/build.gradle
> +
Remove extra lines

2017-03-31 20:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/Di/PracticeApplication.java
> +package com.globant.practice.Di;
Respect java conventions. Package names must be in lowercase

2017-03-31 20:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/Di/PracticeApplication.java
> +public class PracticeApplication extends Application {
Application class is not part of dependency injection

2017-03-31 20:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/View/Activities/SplashActivity.java
> +public class SplashActivity extends AppCompatActivity {
Add javadoc of this class.

2017-03-31 20:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/Presenter/SplashPresenter.java
> +    SplashActivity splash;
The presenter MUST NOT know of Android framework. So it should not handle activities, context, resources or any other Android component

2017-03-31 20:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/Presenter/SplashPresenter.java
> +    SplashActivity splash;
Use an interface that exposes View operations

2017-03-31 20:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/Presenter/SplashPresenter.java
> +    private int timeToWait = 3500;
This value must be a constante.

2017-03-31 20:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/Presenter/SplashPresenter.java
> +    private boolean firstTime = true;
What's the purpose of this?

2017-03-31 20:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/Presenter/SplashPresenter.java
> +        firstTime = false;
Actually, you're not detaching any view

2017-03-31 20:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/Presenter/SplashPresenter.java
> +    public void countTime() {
Define a better name for this method, what it's it purpose?

2017-03-31 20:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/Presenter/SplashPresenter.java
> +    public void attachView(SplashActivity splash) {
The attach should not work with an Activity or Fragment instance.

2017-03-31 20:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/View/Activities/SplashActivity.java
> +        presenter.attachView(this);
Attach the view properly based on the lifecycle of the Activity

2017-03-31 20:36 UTC, daniellemariani commented on app/src/main/res/layout/activity_splash.xml
> +        android:textSize="34dp"/>
Dimensions must be defined inside of a resource file

2017-03-31 20:36 UTC, daniellemariani commented on app/src/main/res/values-en/strings.xml
> +    <string name="app_name">Practice</string>
It's not necessary to defined a *-en* folder, you can use these strings from default strings.

2017-03-31 20:36 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/SplashPresenterTest.java
> + * Created by jonathan.vargas on 31/03/2017.
Add javadoc

2017-03-31 20:36 UTC, daniellemariani commented on gradle.properties
> +systemProp.http.proxyHost=proxy.corp.globant.com
Please, avoid committing this.

2017-03-31 20:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/View/Activities/HomeActivity.java
> +public class HomeActivity extends AppCompatActivity {
Add javadoc

2017-03-31 20:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/Presenter/SplashPresenter.java
> + * Created by jonathan.vargas on 30/03/2017.
Add javadoc

2017-03-31 20:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/Di/PracticeModule.java
> + * Created by jonathan.vargas on 30/03/2017.
Add javadoc

2017-03-31 20:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/Di/PracticeApplication.java
> + * Created by jonathan.vargas on 30/03/2017.
Add javadoc

2017-03-31 20:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/Di/ApplicationComponent.java
> + * Created by jonathan.vargas on 30/03/2017.
Add javadoc

2017-03-31 20:36 UTC, daniellemariani commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".View.Activities.SplashActivity">
Same here. Package names must be defined in lowercase

2017-03-31 23:44 UTC, daniellemariani requested changes

2017-03-31 23:44 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/PracticeApplication.java
> +
Remove extra line

2017-03-31 23:44 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/di/PracticeModule.java
> + * Provide all the possible reference that Dagger can inject.
It provides*

2017-03-31 23:44 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presenter/SplashPresenter.java
> +    Splash splash;
If this a View, it would be better to give it a more descriptive name like _view_ for instance

2017-03-31 23:44 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presenter/SplashPresenter.java
> +    Splash splash;
If this attribute is only use here, it would be better make it private

2017-03-31 23:44 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presenter/SplashPresenter.java
> +    Timer t;
If this attribute is only use here, it would be better make it private

2017-03-31 23:44 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/view/activities/HomeActivity.java
> + * Initialize the components of the activity_splash UI and manage the communication
Splash Activity? Presenter?

2017-03-31 23:44 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presenter/SplashPresenter.java
> +                    splash.changeView();
what if there is a detach before getting in this line. I think you'll get a NPE

2017-04-03 21:11 UTC, daniellemariani requested changes

2017-04-03 21:11 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/interfaces/Splash.java
> +public interface Splash {
If this Splash represents a view inside MVP, please place it into a **view** package. Also, it may have View as a suffix in the name.

2017-04-03 21:11 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presenter/SplashPresenter.java
> +                    if (verifyIfTheViewExist())
I know it's valid. But please, always use the braces **{ }**

2017-04-03 21:11 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presenter/SplashPresenter.java
> +    private boolean verifyIfTheViewExist() {
Use a better name like _isViewAttached_.

2017-04-03 21:11 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presenter/SplashPresenter.java
> +        if (view != null)
It's not necessary to use _if/else_ statement. Pay attention to the condition.

2017-04-03 21:11 UTC, daniellemariani commented on gradle.properties
> -# Project-wide Gradle settings.
Do not remove this file

2017-04-03 22:25 UTC, jvc931 commented on gradle.properties
> -# Project-wide Gradle settings.
The last commit has this file.

2017-04-03 22:36 UTC, daniellemariani requested changes

2017-04-03 22:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presenter/SplashPresenter.java
> +            return view != null;
Check code format. Also, the article *the* is not necessary in method names, that's why I suggested isViewAttached.

2017-04-03 22:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/view/activities/SplashActivity.java
> +        Intent toHome = new Intent(SplashActivity.this, HomeActivity.class);
You can use *this* without referencing the class.

2017-04-03 22:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/view/activities/SplashView.java
> + * Work to decouple the view of the presenter.
It work**S**

2017-04-03 22:36 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/view/activities/SplashView.java
> +public interface SplashView {
👍

2017-04-04 14:32 UTC, daniellemariani requested changes

2017-04-04 14:32 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presenter/SplashPresenter.java
> +    private static final int timeToWait = 3500;
constants generally are written in uppercase with "_"

2017-04-04 14:32 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presenter/SplashPresenter.java
> +    private Timer t;
Choose a more descriptive name for this

2017-04-04 14:32 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/presenter/SplashPresenter.java
> +    public void attachView(SplashView splash) {
I would rather call this parameter _view_

2017-04-04 14:32 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/view/activities/HomeActivity.java
> +     * Initialize the UI components and the presenter instance.
Initializes*

2017-04-04 14:32 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/view/activities/HomeActivity.java
> + * Initialize the components of the activity_home UI and manage the communication
Initializes

2017-04-04 14:32 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/view/activities/SplashActivity.java
> + * Initialize the components of the activity_splash UI and manage the communication
Initializes... and manages

2017-04-04 14:32 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/view/activities/SplashView.java
> +     * Create and start the intent to change the view to HomeActivity.
Creates and starts*

2017-04-04 14:32 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/SplashPresenterTest.java
> +            e.printStackTrace();
Avoid printing full stack trace

2017-04-04 14:32 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/SplashPresenterTest.java
> +    Splash mockView = Mockito.mock(Splash.class);
You can use @Mock annotation and in the setup initialize the mocks

2017-04-04 14:32 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/SplashPresenterTest.java
> +        presenter.attachView(mockView);
I think you're missing something. How do you check if the view is properly attached?

2017-04-04 17:09 UTC, daniellemariani requested changes

2017-04-04 17:09 UTC, daniellemariani commented on app/src/main/java/com/globant/practice/view/activities/SplashView.java
> +    void changeView();
Perhaps a name like navigateToHome is more descriptive than changeView

2017-04-04 17:09 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/presenter/SplashPresenterTest.java
> +import static org.junit.Assert.*;
Avoid using * for imports

2017-04-04 17:09 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/presenter/SplashPresenterTest.java
> +    private SplashPresenter presenter;
You can @Mock this as well

2017-04-04 17:09 UTC, daniellemariani commented on app/src/test/java/com/globant/practice/presenter/SplashPresenterTest.java
> +        }catch (NullPointerException e){
check code format

2017-04-04 18:25 UTC, daniellemariani approved these changes
LG

2017-04-04 18:25 UTC, merged